"""领域常量：状态、规则码、限额。与主设计 §4/§11/§16 对齐。"""
from __future__ import annotations

SCHEMA_VERSION = "0.1.0"

# ---- 费用代码与公式（封闭枚举，§8.3/§9）----
CHARGE_BASE = "BASE"
CHARGE_WAIT = "WAIT"
CHARGE_TOLL = "TOLL"
CHARGE_CODES = (CHARGE_BASE, CHARGE_WAIT, CHARGE_TOLL)
FORMULA_FOR_CHARGE = {CHARGE_BASE: "PER_TRIP", CHARGE_WAIT: "WAIT_BLOCKS",
                      CHARGE_TOLL: "ACTUAL_RECEIPT"}
FORMULAS = ("PER_TRIP", "WAIT_BLOCKS", "ACTUAL_RECEIPT")

# ---- 匹配（§7.2）----
MATCH_EXACT = "EXACT"
MATCH_CONFIRMED = "CONFIRMED"
MATCH_AMBIGUOUS = "AMBIGUOUS"
MATCH_UNMATCHED = "UNMATCHED"
MATCH_CONFLICT = "CONFLICT"
MATCH_OUT_OF_SCOPE = "OUT_OF_SCOPE"
MATCH_STATES = (MATCH_EXACT, MATCH_CONFIRMED, MATCH_AMBIGUOUS, MATCH_UNMATCHED,
                MATCH_CONFLICT, MATCH_OUT_OF_SCOPE)
# 仅这两态可进入可比计算
COMPARABLE_MATCH_STATES = (MATCH_EXACT, MATCH_CONFIRMED)

# ---- 三个正交状态维度（§11.2）----
COMPARABLE = "COMPARABLE"
NOT_COMPARABLE = "NOT_COMPARABLE"
EVIDENCE_COMPLETE = "COMPLETE"
EVIDENCE_MISSING = "MISSING"
EVIDENCE_CONFLICT = "CONFLICT"

REVIEW_OPEN = "OPEN"
REVIEW_CONFIRMED_DIFFERENCE = "CONFIRMED_DIFFERENCE"
REVIEW_ACCEPTED_AS_BILLED = "ACCEPTED_AS_BILLED"
REVIEW_NEEDS_EVIDENCE = "NEEDS_EVIDENCE"
REVIEW_DISPUTED = "DISPUTED"
REVIEW_OUT_OF_SCOPE = "OUT_OF_SCOPE"
REVIEW_STALE = "STALE"

# ---- 资产/来源类别（§5.1 六类输入）----
ASSET_BILL = "bill"
ASSET_TRIPS = "trips"
ASSET_RATES = "rates"
ASSET_WAITING = "waiting"
ASSET_RECEIPTS = "receipts"
ASSET_POD = "pod"
ASSET_HISTORY_TRIPS = "history_trips"
ASSET_KINDS = (ASSET_BILL, ASSET_TRIPS, ASSET_RATES, ASSET_WAITING, ASSET_RECEIPTS,
               ASSET_POD, ASSET_HISTORY_TRIPS)

# ---- 异常规则码（§11.1，15 类 21 码）----
ISSUE_SOURCE_TOTAL_MISMATCH = "SOURCE_TOTAL_MISMATCH"
ISSUE_PARSE_FAILED = "PARSE_FAILED"
ISSUE_ID_DAMAGED = "ID_DAMAGED"
ISSUE_UNMATCHED = "UNMATCHED"
ISSUE_AMBIGUOUS = "AMBIGUOUS"
ISSUE_CARRIER_CONFLICT = "CARRIER_CONFLICT"
ISSUE_RATE_NOT_FOUND = "RATE_NOT_FOUND"
ISSUE_RATE_AMBIGUOUS = "RATE_AMBIGUOUS"
ISSUE_BASIS_MISMATCH = "BASIS_MISMATCH"
ISSUE_AMOUNT_HIGH = "AMOUNT_HIGH"
ISSUE_AMOUNT_LOW = "AMOUNT_LOW"
ISSUE_DUPLICATE_SUSPECT = "DUPLICATE_SUSPECT"
ISSUE_MISSING_POD = "MISSING_POD"
ISSUE_POD_CONFLICT = "POD_CONFLICT"
ISSUE_MISSING_RECEIPT = "MISSING_RECEIPT"
ISSUE_WAIT_EVIDENCE_INVALID = "WAIT_EVIDENCE_INVALID"
ISSUE_REVERSAL_INVALID = "REVERSAL_INVALID"
ISSUE_HISTORICAL_DUPLICATE_CANDIDATE = "HISTORICAL_DUPLICATE_CANDIDATE"
ISSUE_NOT_BILLED_IN_PROVIDED_SCOPE = "NOT_BILLED_IN_PROVIDED_SCOPE"
ISSUE_UNSUPPORTED = "UNSUPPORTED"
ISSUE_OUT_OF_SCOPE = "OUT_OF_SCOPE"
# 参考引擎语义保留码（测试对齐用）
ISSUE_RULE_UNCONFIRMED = "RULE_UNCONFIRMED"
ISSUE_TRIP_NOT_EXECUTED = "TRIP_NOT_EXECUTED"
ISSUE_CURRENCY_UNSUPPORTED = "CURRENCY_UNSUPPORTED"
ISSUE_UNSUPPORTED_FORMULA = "UNSUPPORTED_FORMULA"
ALL_ISSUE_CODES = frozenset({
    ISSUE_SOURCE_TOTAL_MISMATCH, ISSUE_PARSE_FAILED, ISSUE_ID_DAMAGED, ISSUE_UNMATCHED,
    ISSUE_AMBIGUOUS, ISSUE_CARRIER_CONFLICT, ISSUE_RATE_NOT_FOUND, ISSUE_RATE_AMBIGUOUS,
    ISSUE_BASIS_MISMATCH, ISSUE_AMOUNT_HIGH, ISSUE_AMOUNT_LOW, ISSUE_DUPLICATE_SUSPECT,
    ISSUE_MISSING_POD, ISSUE_POD_CONFLICT, ISSUE_MISSING_RECEIPT,
    ISSUE_WAIT_EVIDENCE_INVALID, ISSUE_REVERSAL_INVALID,
    ISSUE_HISTORICAL_DUPLICATE_CANDIDATE, ISSUE_NOT_BILLED_IN_PROVIDED_SCOPE,
    ISSUE_UNSUPPORTED, ISSUE_OUT_OF_SCOPE, ISSUE_RULE_UNCONFIRMED,
    ISSUE_TRIP_NOT_EXECUTED, ISSUE_CURRENCY_UNSUPPORTED, ISSUE_UNSUPPORTED_FORMULA,
})

# ---- 状态机（§16.1）----
CASE_DRAFT = "DRAFT"
CASE_READY = "READY"
CASE_RUNNING = "RUNNING"
CASE_REVIEW_REQUIRED = "REVIEW_REQUIRED"
CASE_FROZEN = "FROZEN"
CASE_ARCHIVED = "ARCHIVED"
CASE_STATUSES = (CASE_DRAFT, CASE_READY, CASE_RUNNING, CASE_REVIEW_REQUIRED, CASE_FROZEN,
                 CASE_ARCHIVED)

JOB_QUEUED = "QUEUED"
JOB_RUNNING = "RUNNING"
JOB_SUCCEEDED = "SUCCEEDED"
JOB_PARTIAL = "PARTIAL"
JOB_FAILED = "FAILED"
JOB_CANCELLED = "CANCELLED"
JOB_STATUSES = (JOB_QUEUED, JOB_RUNNING, JOB_SUCCEEDED, JOB_PARTIAL, JOB_FAILED,
                JOB_CANCELLED)

OBJECT_DRAFT = "DRAFT"
OBJECT_CONFIRMED = "CONFIRMED"
OBJECT_SUPERSEDED = "SUPERSEDED"

EXPORT_PREPARED = "PREPARED"
EXPORT_RELEASED = "RELEASED"
EXPORT_DOWNLOADED = "DOWNLOADED"

RUN_SUCCEEDED = "SUCCEEDED"
RUN_PARTIAL = "PARTIAL"
RUN_FAILED = "FAILED"
RUN_RUNNING = "RUNNING"

# ---- pod 证据状态 ----
POD_VERIFIED = "VERIFIED"
POD_MISSING = "MISSING"
POD_CONFLICT = "CONFLICT"
POD_UNPROVIDED = "UNPROVIDED"  # 用户未提供履约凭证索引：不算 MISSING，进入覆盖缺口
POD_STATES = (POD_VERIFIED, POD_MISSING, POD_CONFLICT, POD_UNPROVIDED)

# ---- 限额（§6.1，待压测的配置目标）----
MAX_FILE_BYTES = 25 * 1024 * 1024
MAX_FILES_PER_CASE = 10
MAX_DETAIL_ROWS_PER_FILE = 50_000
MAX_BILL_LINES_PER_CASE = 100_000
MAX_CELL_TEXT = 100_000
XLSX_MAX_SHEETS = 64

# ---- 分页（api-contracts）----
DEFAULT_PAGE_LIMIT = 50
MAX_PAGE_LIMIT = 100
